### ISSUE TITLE
MT5 2.34 Infinite automatic switch between tiles when PSC is minimized

### ISSUE THREAD

**Issue by frenchdna** [EarnForex/PositionSizeCalculator#11]
Hi there and thanks for a fantastic tool that I use everyday.

I was excited by the changelog of v2.34 as it solves a couple of inconveniences that drove me nuts (that Stop Line! lol) but halas I'm running into an issue before I even get to use the tool properly. 

This is on MT5, v2.34. The moment the indicator is minimised, there seems to be an automatic loop on that pulls focus back on this pair/tab/tile. 
If I load the indicator on a 2nd pair and minimise the panel there then MT5 just automatically switches between the 2 pairs that have the indicator minimised. It gets worse if I can load it on a 3rd pair, it switches between the 3 so fast. It becomes impossible to do anything. The behaviour stops when the panel is "opened" or "maximised". 

I've restarted MT5 several times, unloaded the indicator properly, loaded it back up and the same behaviour appears everytime. This is on default settings.

It doesn't happen on MT4 v2.34.

**Comment by EarnForex** [comment]
Thanks for reporting. The MT5 version has been updated to 2.35 to fix this issue. Please re-download and try it.

**Comment by frenchdna** [comment]
Thanks for the quick fix!
