### ISSUE TITLE
PSC-Trader Script Issue

### ISSUE THREAD

**Issue by jorap** [EarnForex/PositionSizeCalculator#13]
Hi Team,

I upgraded to the latest version (2.34) for MT4. When I set the order to Long or Short with Order set to Instant, my order is a Buy Limit. Please refer to the screenshot shown below.

I reverted back to version 2.28 and I set the order to Buy with Order set to Instant, my order is a Buy.

Thanks in advance.

Regards,

Jon

![234 issue](https://user-images.githubusercontent.com/4858188/113631078-790e2700-969b-11eb-8be9-999082b6fa98.png)

**Comment by EarnForex** [comment]
Hi Jon,

Please see this issue and the proposed solution:
https://github.com/EarnForex/PositionSizeCalculator/issues/9
