### ISSUE TITLE
manually adjustable TP1 line

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizeCalculator#14]
hello dear developer, is it possible to have an adjustable TP1 line? right now it gets overrides when it moved manually to TP ratio input level.  i couldn't find any settings to do that. 

thanks in advance

**Comment by EarnForex** [comment]
Hello!

How do you do that? Here is how it works:
![psc](https://user-images.githubusercontent.com/48102957/118286670-5c0b1600-b4db-11eb-9d89-7eb9daf67547.gif)

**Comment by paymanz** [comment]
> 
> 
> Hello!
> 
> How do you do that? Here is how it works:
> ![psc](https://user-images.githubusercontent.com/48102957/118286670-5c0b1600-b4db-11eb-9d89-7eb9daf67547.gif)

you're right , later when i tried it worked like you showed here. but before that it didn't let me manually move it. maybe its because i change the symbol on the same chart.  thanks for respond anyways.

**Comment by EarnForex** [comment]
Perhaps, you had ATR-based TP enabled?

**Comment by paymanz** [comment]
> 
> 
> Perhaps, you had ATR-based TP enabled?

oh no!

btw here is a gif showing how it looks like when it happens. if i remove the indicator from chart and add it again the problem will be solved. 

![aaaaa13](https://user-images.githubusercontent.com/10323812/119312680-e85dcb80-bc87-11eb-8084-f9b361392d69.gif)

**Comment by EarnForex** [comment]
You probably had Take-profit button locked on SL distance (dark gray TP button on the Main tab).

**Comment by paymanz** [comment]
> 
> 
> You probably had Take-profit button locked on SL distance (dark gray TP button on the Main tab).

oh thank you that's it , problem solved!

**Comment by EarnForex** [comment]
Glad this solved the issue!
