### ISSUE TITLE
TP levels based on symbols on a chart with symbol changer indicator

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizeCalculator#15]
Hi , thanks for this great free indicator you provided for us, can i please request to add a feature to adjust TP levels according to different symbols?  right now if you change the symbol on the current chart the TP levels remain on price levels of previous symbol. 

cheers

**Comment by EarnForex** [comment]
Hi!

How should it know where to place the TPs on the new symbol? There are plenty of ways to move the TPs to your desired levels.

**Comment by paymanz** [comment]
> 
> 
> Hi!
> 
> How should it know where to place the TPs on the new symbol? There are plenty of ways to move the TPs to your desired levels.

Hi , i few a few ways i would suggest:
-initial TPs calculated based on SL (1R,2R,3R,...) and then user can move them.
- small percentage so the TPs wont be so far away and user can see them on chart and edit them as desired. 
-as the panel has other symbol specific function(it remembers panel position) it could remember the TPs position of each symbol maybe , but again it need initial values , so the first 2 options above.

Thank you :)

**Comment by EarnForex** [comment]
I'll consider adding something like this, but I am not sure yet...

**Comment by EarnForex** [comment]
Fixed in 2.38.
