### ISSUE TITLE
Unable to add Points Value for TP2 or TP3 with Version 2.37

### ISSUE THREAD

**Issue by KamThind** [EarnForex/PositionSizeCalculator#16]
Hi, 

I updated to the latest version (2.37) today, and I have tried to add 2 take profits using the ScriptTakeProfitsNumber function, however when I try to define how many points away I would like the Take Profit to be the number is automatically changing to another number. For example, my take profit 1 is 300 points (this can be changed to whatever I like and stays the same), my take profit 2 I tried to put in 600 points but as soon as it is entered it changes to 59922345. I think you have a bug here, but I apologise if this is something on my end, but I am not sure what this could be at the moment.

If there is another way I can place one trade and have a partial profit automatically triggered at a predefined level using your app please let me know. Thank you

**Comment by EarnForex** [comment]
Yeah, there is a bug. Thanks for reporting! I will fix it in the next version.

**Comment by EarnForex** [comment]
Fixed in 2.38.
