### ISSUE TITLE
Please consider making the account balance editable

### ISSUE THREAD

**Issue by theghostinplainsight** [EarnForex/PositionSizeCalculator#17]
Hi, thank you for the wonderful indicator.

Please make the account balance to based on the user's input instead of just grabbing it automatically.  Or better yet, maybe a button to switch between automatically getting and manually inputing the account balance. 

   Having to go to additional funds every time to add the difference between accounts is not convenient and really slows things down. Especially when you are working with multiple charts and you need to quickly take trades.

Once again, thank you for the indicator.

**Comment by EarnForex** [comment]
Thanks! I will see if that's doable.

**Comment by EarnForex** [comment]
Fixed in 2.38.
