### ISSUE TITLE
NZDCHF Wrong Position Sizes

### ISSUE THREAD

**Issue by itsnotyoutoday** [EarnForex/PositionSizeCalculator#19]
On NZDCHF for FundingTalent's demo server this is giving me the wrong position sizes.  i.e. it is giving me 600 & 1200 lot size suggestions which is way more than possible..  Any tips on debugging what might be giving the wrong data?

**Comment by EarnForex** [comment]
Hi!

Is it MT4 or MT5? Which account currency do you use? Could you please attach the screenshot of the NZDCHF contract specification from MetaTrader? Assuming you are on MT4, could you please run the attached script on an NZDCHF chart?
[Demo-1.zip](https://github.com/EarnForex/PositionSizeCalculator/files/6732381/Demo-1.zip)

**Comment by itsnotyoutoday** [comment]
Account currency is USD.  If its any help. I find if i knock off a zero its right (i.e. if it tells me to use 500 lots, use 50 lots).  Is the script you mentioned going to try to execute a trade or just gather information?

![image](https://user-images.githubusercontent.com/10070062/123799985-a125b480-d89d-11eb-821a-e0e059e5ff3f.png)

**Comment by EarnForex** [comment]
The script will just print out the MODE_TICKVALUE to the Experts tab of the Terminal subwindow. It won't execute any trades.

**Comment by EarnForex** [comment]
Sorry, it looks like you attached the contract specification for a wrong pair (AUDNZD instead of NZDCHF).

**Comment by itsnotyoutoday** [comment]
Opps..  Just woke up.  script says ticke value 0.1

![image](https://user-images.githubusercontent.com/10070062/123802017-ab48b280-d89f-11eb-948d-f13ae7fccd65.png)

**Comment by EarnForex** [comment]
OK, it looks like your broker reports incorrect TickValue to MQL4 programs on that pair. TickValue should always be equal to the actual value of 1 tick movement in account currency. For you, it should have reported something like 1.0852. Unfortunately, this isn't possible to correct from inside the PSC, but you could try contacting your broker about this issue.

**Comment by itsnotyoutoday** [comment]
I tell them something is wrong on their end and Logan from there says its the indicator and to use another one.  I ask well, which one cause I used 3 they can't recommend any and to use a web based one... I love how most tech support people are useless and don't know how to actually fix anything....
