### ISSUE TITLE
Doesn't display spread and neither count them

### ISSUE THREAD

**Issue by ahamyogi** [EarnForex/PositionSizeCalculator#21]
It is a beautiful indicator, but it doesn't show spreads and neither counts them. Making the size wrong

**Comment by EarnForex** [comment]
Hello!

You can enable spread display via the **ShowSpread** input parameter.

However, the spread shouldn't be used in position size calculation. Whatever the spread is, you are always risking the stop-loss you are setting for your trade. E.g., if you set stop-loss to 10 pips, you will lose 10 pips regardless of what your spread is.

**Comment by ahamyogi** [comment]
> Hello!
> 
> You can enable spread display via the **ShowSpread** input parameter.
> 
> However, the spread shouldn't be used in position size calculation. Whatever the spread is, you are always risking the stop-loss you are setting for your trade. E.g., if you set stop-loss to 10 pips, you will lose 10 pips regardless of what your spread is.

Thank you for your kind reply, but does the indicator take the spread in its risk and position calculation?

**Comment by EarnForex** [comment]
The thing is the indicator doesn't have to take the spread in its risk and position calculation. The risk depends on the stop-loss value, not the spread value.
