### ISSUE TITLE
Not possible to have 0 as default SL to disable initial SL line

### ISSUE THREAD

**Issue by hstorz** [EarnForex/PositionSizeCalculator#24]
I am not able to save the config that I have no initial SL line. When I set the value of (SL: Default stop-loss value) to 0 and save the template, the next time I load the chart I have a SL line again. When I set a value to 100 it is saved correctly and applies on every chart with the correct value, just saving 0 to disable it does not work. 

Another problem that I have is: when I manully override the default calculated SL on the main tab to 0 to get rid of the SL line I can not run the PSC Script since it returns a warning: Stop-Loss Line not found! 

I would really appreciate to know how to trade without initial SL line.

I use latest v2.39.

**Comment by EarnForex** [comment]
You cannot disable the SL line. It is required for the Position Size Calculator to work.

**Comment by hstorz** [comment]
Ok thanks for the quick reply. For my use case : I just want to quickly know how many shares I can buy for x amount of Euro. And that works on the main tab correctly without SL. So I thought this will also be able to trigger the trade with the correct position size. Thanks for clarification, then I will place the trade with the default MT UI und use your tool just for quick calculation and look up the max position size on the margin tab.

**Comment by EarnForex** [comment]
You can check the maximum position size by margin on the Margin tab regardless of what your SL is set to.

**Comment by EarnForex** [comment]
This isn't something likely to get implemented.
