### ISSUE TITLE
Compile Error!

### ISSUE THREAD

**Issue by AliGhIO** [EarnForex/PositionSizeCalculator#25]
Hi,
I want to chnage something and add some other features to this awesome tools. But when I compile at first time (without any change) I get this compile error!

![image](https://user-images.githubusercontent.com/45061919/132117748-a88841be-cb36-49b5-a5f1-4cb7caa5e97d.png)

How can I fix this?

**Comment by EarnForex** [comment]
Which file are you trying to compile?

**Comment by AliGhIO** [comment]
> Which file are you trying to compile?

Oh, I found problem. Sorry I just pressed compile on .mqh file.
