### ISSUE TITLE
PSC-Trader USDJPYmicro,H4: Execution failed. Error: 4109 - trade is not allowed in the expert properties.

### ISSUE THREAD

**Issue by Jaytec** [EarnForex/PositionSizeCalculator#3]
When running the PSC-Trader script I get Error: 4109. What does that error mean?

**Comment by alexter6277** [comment]
Hi Jaytec, a quick google search shows you that it means your mt4 terminal, script/EA and or your broker has automated trading disabled. 

You have to make sure you have automated trading enabled, and that your broker allows it (some rare cases have this blocked)

**Comment by Jaytec** [comment]
Thanks! This solved my problem.
