### ISSUE TITLE
Take Profit and Stop Loss Lines not Setting Correctly (Ver. 2.41)

### ISSUE THREAD

**Issue by KamThind** [EarnForex/PositionSizeCalculator#31]
Hi, 

While setting up a trade, when I try and move the stop loss or take profit line with my mouse, on the chart, I set where I would like the SL or TP to be, the lines skip back to where they were before I moved them. The only way I seem to be able to move them, without the lines skipping back to where they were, is by moving the lines as quickly as possible, and even then it takes me a couple of tries. The lines seem to skip back when the price changes, so in calmer hours it's not much of a problem, but when price is moving a little, it's a bit of a challenge. 

Not a big issue to be honest, as I can type in the price or points in the GUI, but it would be nice if this worked a bit smoother. 

Thank you for the great application.

**Comment by EarnForex** [comment]
Hello!

Which MetaTrader version are you experiencing this in? What order type do you use? Do you have **ShowATROptions** set to _true_? Do you have **SLDistanceInPoints** or **TPDistanceInPoints** set to _true_?

**Comment by KamThind** [comment]
Hi, 

I am experiencing this in both MT4 (Version 4.00 build 1350) and MT5 (Version 5.00 build 3091).

Order type is either Instant, Pending or Stop Limit. I have the same issue with all three. 
 
ShowATROptions - set to False
SLDistanceInPoints - set to True
TPDistanceInPoints - set to True


Sometimes I will set my TP or SL using  Points and  other times I  move the lines  with my mouse

**Comment by EarnForex** [comment]
OK, I see the problem. I will look into it.

**Comment by EarnForex** [comment]
Fixed in 2.42.
