### ISSUE TITLE
suggestion to have a auto commentary for orders

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizeCalculator#32]
Hi Earnforex  , i have a suggestion to have commentary for each trade based on symbol and time.

something like "EURUSD BUY 1 - 1.1.2022" , "EURUSD BUY 2 - 1.1.2022" and so on , for each day it numbers each buy or sell position(or if numbering each trade is not possible it could be a random number so trades can be differentiable from each other ). that would be really cool for journal and analyzing trades.

hope that make sense and possible to do.

Thank you

**Comment by EarnForex** [comment]
Symbol, direction, and price are already a part of the trade information - both in the Trade tab and the reports produced by MetaTrader. What is the point of adding this information to order commentary?

By the way, you can use the Commentary field in the Script tab of the PSC panel to fill in the commentary of your choice.

**Comment by paymanz** [comment]
> Symbol, direction, and price are already a part of the trade information - both in the Trade tab and the reports produced by MetaTrader. What is the point of adding this information to order commentary?
> 
> By the way, you can use the Commentary field in the Script tab of the PSC panel to fill in the commentary of your choice.

i forgot to mention it can be specially useful when you break each trade in smaller positions(multiple TPs) and you may have scaled out in different levels , so when analyzing performance you can see how each trade performed , it is multiple positions but actually one trade. so it helps with that.

**Comment by EarnForex** [comment]
Thanks, I'll consider what can be done with it.

**Comment by paymanz** [comment]
> Fixed in 2.42.

hi , the auto suffix input seems to not working. meaning every time you open a new chart need to tick the check box in the script tab. can you please fix it?

**Comment by EarnForex** [comment]
This is fixed in 3.02.

**Comment by paymanz** [comment]
> This is fixed in 3.02.

sorry i just found that you turned it into an EA?! im confused! what about the PSC indicator/script?!

**Comment by paymanz** [comment]
any chance you fix this issue for the indicator please?

**Comment by EarnForex** [comment]
Currently, I am not planning to work on the indicator/script. Maybe in the future, I will publish something like a maintenance release, but I wouldn't count on it.

**Comment by aamoraru** [comment]
That's definitely an idea to consider!
