### ISSUE TITLE
一键挂单

### ISSUE THREAD

**Issue by ian0513** [EarnForex/PositionSizeCalculator#34]
您好，PositionSize中如果默认挂单线设在前一根蜡烛高低点就更棒了。也就是以孕线形式的蜡烛突破高低点设buystop或sellstop挂单线，止损线设在孕线另一边。buystop挂单：孕线蜡烛上方+2点+点差，止损在孕线下方-2点；sellstop挂单：孕线蜡烛下方-2点，止损在孕线上方+2点+点差。如果默认挂单线能这样设置，将极大方便快速突破交易的挂单。请老师参考一下，谢谢！

**Comment by EarnForex** [comment]
Hello!

I google-translated your request, so I might have misunderstood, but from what I've read you ask the entry/TP/SL to be set to specific kind of levels when switching PSC to a Pending order mode. The problem I see with this is that it would nudge traders into trading using this particular way - this is something I am trying to avoid with the indicator. Hence it doesn't suggest any levels when switching to a Pending order mode.

**Comment by ian0513** [comment]
模式1.instant ；模式2.pending；模式3.inside :默认（可选）buystop孕线高点+点差+2点，止损孕线低点-2点；sellstop 孕线低点-2点，止损孕线高点+点差+2点。期待您的升级版本，谢谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: EarnForex ***@***.***&gt;
发送时间: 2022年1月23日 00:54
收件人: EarnForex/PositionSizeCalculator ***@***.***&gt;
抄送: ian0513 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EarnForex/PositionSizeCalculator] 一键挂单 (Issue #34)





 
Closed #34.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
