### ISSUE TITLE
Some suggestions for the UI

### ISSUE THREAD

**Issue by anjari** [EarnForex/PositionSizeCalculator#35]
Hi, I have some suggestions:

(1) For the textfields marked by red circle below:

![image](https://user-images.githubusercontent.com/15816154/151659592-24e5db71-0b82-4939-93e7-68ea536322a9.png)

Could you make the textfield values auto-calculated when users are typing on the textfields? Currently I have to press Enter or switching the textfield focus (by pressing TAB key or clicking other textfield) to trigger the calculation, so if the values can be calculated automatically, it will be more convenient.

(2) Shows pips/points difference information between the SL/TP & Entry price on the main window.

**Comment by EarnForex** [comment]
Hi!

I'll think about the (1). Not sure if this is possible with MQL4/5.

(2) I don't think it's a good idea. One can already switch to pips display and see the pips distances near the lines.

**Comment by anjari** [comment]
About the (2), you're right, there is already pips/points distance info shown near the lines, I didn't realize that.

Another minor issue: if I have the PositionSizeCalculator's SL & TP lines shown in the currency chart (e.g. EURUSD) and if I use [Symbol Changer Profit Display v5.1](https://www.forexfactory.com/thread/703669-symbol-changer-profit-display) indicator to switch the chart to indices chart (e.g. US30) and then switch back to the previous currency chart, the SL & TP pips distance labels will get shifted a bit to the right.

![image](https://user-images.githubusercontent.com/15816154/151662182-2cde59de-5cfc-4d81-8e1c-e216012927f7.png)

Although this can be corrected by switching the timeframe back and forth, but I still think it's better if this can be fixed.

**Comment by EarnForex** [comment]
That's weird. I will look into this. Thanks for reporting!

**Comment by EarnForex** [comment]
Hello again!

(1) Looks impossible as the actual object's text value doesn't change until you press Enter/Tab.

**Comment by anjari** [comment]
I see, that's unfortunate.

**Comment by EarnForex** [comment]
(2) fixed in 2.42.
