### ISSUE TITLE
lot size calculation issue with a particular broker jpy pairs

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizeCalculator#37]
hi dear developer , on this broker M4markets i get wrong calculation for JPY pairs , i know PSC works correct on every other broker i have ever tried and probably something is weird about this broker's servers , i have explained this issue with their support but they don't seem to be even understanding it. 

i don't know if that possible or not but can PSC adapt to these type of brokers in next updates please?

**Comment by EarnForex** [comment]
Hi!

Is it in MT4 or MT5? What type of account do you have with them? What is your account currency?

**Comment by paymanz** [comment]
> Hi!
> 
> Is it in MT4 or MT5? What type of account do you have with them? What is your account currency?

it is MT4 and account type "Raw spread" , account currency is USD.

**Comment by EarnForex** [comment]
Thanks! I will look what can be done.

**Comment by EarnForex** [comment]
OK. In theory, I could circumvent this by detecting that quote currency != account currency but the reported tick value = 1 account currency unit. Then, the PSC could find the actual conversion pair (USD/JPY in your case) and then calculate the correct tick value.

However, this wouldn't work in M4Markets, because their misconfigured server reports Base Currency as AUD for nearly all currency pairs, even for those that have nothing to do with AUD (e.g., for EUR/CHF). So, searching for a conversion currency pair will fail based on Base/Profit Currencies.

It could be further circumvented by analyzing the symbol name, but I don't really like this way - it is slower and not foolproof due to prefixes/suffixes.

**Comment by paymanz** [comment]
oh ok , thanks for investigating this issue , appreciate it.

yeah making PSC slower and inefficient in calculation for just one broker doesn't worth it for sure.

**Comment by paymanz** [comment]
> On those two other brokers, is there any output in the Experts tab of the Terminal subwindow? Like about the PSC failing to retrieve a reference pair?

when i reload PSC:
2022.03.02 13:21:27.594	PositionSizeCalculator EURJPY,M5: initialized
2022.03.02 13:21:27.577	PositionSizeCalculator EURJPY,M5: Loaded settings successfully.
2022.03.02 13:21:27.576	PositionSizeCalculator EURJPY,M5: Trying to load settings from file.
2022.03.02 13:21:27.534	PositionSizeCalculator EURJPY,M5: Saved settings successfully.
2022.03.02 13:21:27.532	PositionSizeCalculator EURJPY,M5: Trying to save settings to file: PSC_EURJPY132838627281956975.txt.
2022.03.02 13:21:27.531	PositionSizeCalculator EURJPY,M5: uninit reason 5

**Comment by paymanz** [comment]
on Turnkey when i check EURJPY(has problem) specification it has a tick size field. but on same broker USDJPY doesnt have this field and PSC calculates UJ correctly.
https://i.imgur.com/n7HbWzN.png
https://i.imgur.com/6dN1yqn.png
on M4markets on all jpy pairs they have tick value field and all of them have same problem.

**Comment by paymanz** [comment]
Runwise EA also had this problem, here is their respond:
We’ve had a look at it. The broker isn’t setting the Tick Value correctly. You can see the tick value in CONFIG | Risk / Lots. It’s more wrong on JPY but wrong on other non-USD pairs. When this value is incorrect then can’t work lots from risk pips.


Note, Tick Value is returned by MetaTradre’s MarketInfo() function and it’s the broker’s responsibility to return the correct values: https://book.mql4.com/appendix/marketinfo

You’ll have to either use a different broker or set lots directly in CONFIG | Risk / Lots

**Comment by EarnForex** [comment]
The thing is, the tick_value reported to MQL4 is wrong :-). That's the problem.

**Comment by EarnForex** [comment]
Wow! That's great!
