### ISSUE TITLE
Position size incorrectly calculated when entry button is toggled with ATR SL multiplier

### ISSUE THREAD

**Issue by HeathU** [EarnForex/PositionSizeCalculator#5]
Environment:
- Position Size Calculator version: 2.27
- MT 5.00 build 2361 (8 Mar 2020)

Issue:
Calculated position size when between entry type sell/buy is up to 100x different, e.g. starts at 1.82, click to sell, shows 0.05, click to buy shows 12.79. The position size shown is often invalid for the trading account showing "Not enough money" in MT5.

Steps to recreate:

1. Open EURAUD daily chart
2. Display Position Size Calculator (ShowATROptions: true)
3. Ensure ATR period: 14, SL multiplier: 1.50, ATR timeframe: PERIOD_D1, Risk (%): 2
4. Take note of Position Size
5. Click entry button (labelled "Buy @") changes to "Sell @"
6. Take note of Position Size
7. Click entry button (labelled "Sell @") changes to "Buy @"
8. Take note of Position Size
9. Compare position sizes.

Image1-Startup
![PositionSizeCalculator-MT5-Image1-Startup](https://user-images.githubusercontent.com/4904949/81170259-4858d580-8f92-11ea-85a2-b8cf94e8d1a2.png)

Image2-Sell
![PositionSizeCalculator-MT5-Image2-Sell](https://user-images.githubusercontent.com/4904949/81170261-48f16c00-8f92-11ea-8f3f-741841279cb6.png)

Image3-Buy
![PositionSizeCalculator-MT5-Image3-Buy](https://user-images.githubusercontent.com/4904949/81170262-498a0280-8f92-11ea-8159-721cfc231c3a.png)

**Comment by EarnForex** [comment]
Could you please provide the screenshot of the Experts tab when you are doing this?
I've tried to reproduce the bug (using GBP account and EUR/AUD currency pair) but everything worked as intended. Also, what broker and account type are you using?

**Comment by HeathU** [comment]
I'm using an ICMarketsEU-Demo account with GBP.

I went through the steps to recreate the issue but only see this in the Experts tab...

2020.05.06 15:40:05.417	PositionSizeCalculator (EURAUD,D1)	Trying to load settings from file.
2020.05.06 15:40:05.417	PositionSizeCalculator (EURAUD,D1)	No settings file to load.

**Comment by EarnForex** [comment]
What account type do you use at IC Markets - Raw Spreads or Standard?

Are you sure that the only input parameter you change is **ShowATROptions**? Could you please attach a .set file?

I've just tested it on ICMarkets Standard demo account and it went fine. Please see the attached GIF.
![psc227](https://user-images.githubusercontent.com/48102957/81199957-02b8fe80-8fcc-11ea-9b17-21af33b340fe.gif)

**Comment by HeathU** [comment]
Eek! I do apologise. I've recompiled 2.2.7 again and all seems to be working. I believe this was my mistake as a I changed some default settings and broke the calculation. My bad!

FYI, the settings I want defaulted are ShowATROptions=true and ATRMultiplierSL=1.50 without having to use Load each time across all charts. Is there a way to get MT5 to auto-load .set files for PSC? Looks like in the code PSC is loading settings using symbol and chart id.

**Comment by EarnForex** [comment]
> Looks like in the code PSC is loading settings using symbol and chart id.

Those setting files only store the panel fields' values - not the input parameter settings.

You can save a chart with PSC on it and with your preferred input parameter values to a chart template and load it on a chart. You can save it as a default template to make it load automatically on each new chart.
