### ISSUE TITLE
MT4

### ISSUE THREAD

**Issue by linderseen** [EarnForex/PositionSizeCalculator#8]
After i installed the update and done every step over and over. Still wont work when using script. 
Placing a instant order will place a pending order with all wrong nr. So somethings wrong with the PSC script

**Comment by linderseen** [comment]
https://prnt.sc/vmxxlo made a PSC Trad and you se the nr in box and as it was a instant it still made it penfing and the TP and SL and Price all wrong

**Comment by EarnForex** [comment]
Did you update the script as well? It has also changed (should be version 1.10).

**Comment by linderseen** [comment]
Yes and followed the steps there also.

**Comment by EarnForex** [comment]
If you press Ctrl+B on that chart, do you see there extra SL/TP/Entry lines at those (incorrect) levels? Those could be leftovers from the previous version as the PSC now uses prefixed object names. Just delete those lines.

**Comment by linderseen** [comment]
https://prnt.sc/vmyuty dont se any. Could it be that im using heiko candels?

**Comment by linderseen** [comment]
For me it looks like the EURO50 prices and SL and TP  is the us30 so wiered

**Comment by EarnForex** [comment]
There they are - the top 3 objects (EntryLine, StopLossLine, and TakeProfitLine) are old objects (from the previous version of PSC). Delete them.

**Comment by linderseen** [comment]
Aha okay. How do i delete them hehe

**Comment by linderseen** [comment]
Found it will test

**Comment by linderseen** [comment]
Perfect work great now. Thanks for all the help and have a great weekend.

**Comment by EarnForex** [comment]
Glad it helped! By the way, if you have a chart template with PSC saved, you might also have these old lines saved in the template - you would have to remove them each time you apply the template. The best solution would be to save the template again after removing the lines. If you aren't using templates with PSC, you can disregard this piece of advice.
